project:
  type: website

theme:
  light: flatly
  dark: darkly

website:
  title: "Yuxuan Xie"

  open-graph: true
  favicon: image/home_logo.png

  # margin-header: subscribe.html # 一个订阅的栏，不知道干啥用的
  
  # margin-footer: |
    # ![CUG](image/cug_logo.png)

  repo-url: https://github.com/cug-xyx/cug-xyx.github.io
  repo-actions: [edit, issue]

  back-to-top-navigation: true

  page-footer: 
    background: light
    left: "Copyright 2023, Yuxuan Xie" 
    right: 
      - icon: github
        href: https://github.com/cug-xyx

  navbar:
    background: secondary # 顶端栏的背景色？
    search: true
    left:
      - text: 'Tools'
        menu: 
          - text: "hydroET"
            href: "https://github.com/cug-xyx/hydroET"
          - text: "ggRunoff"
            href: "https://cug-xyx.github.io/ggRunoff/"
          - text: "terraExtra"
            href: "https://github.com/cug-xyx/terraExtra"
      - text: "Publications"
        href: "./articles/Publications.qmd"

    logo: "image/home_logo.png"
    logo-alt: "Home"

    tools:
      # - icon: twitter
      #   href: https://twitter.com
      - icon: github
        menu:
          - text: "Github home"
            url:  https://github.com/cug-xyx
          - text: "Source Code"
            url:  https://github.com/cug-xyx/cug-xyx.github.io

  # ----------------- 侧边栏 ------------------------
  sidebar:
    - title: "Publications"
      background: light
      style: "docked" # floating
      contents:
        - "./articles/ET_evaluation.qmd"
    - title: "Tools"
      background: light
      style: "docked" # floating
      contents:
        - text: "hydroET"
          href: "https://github.com/cug-xyx/hydroET"
        - text: "ggRunoff"
          href: "https://cug-xyx.github.io/ggRunoff/"
        - text: "terraExtra"
          href: "https://github.com/cug-xyx/terraExtra"

execute:
  freeze: auto


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



